CREATE DATABASE IF NOT EXISTS CEIBAL_DB;

USE DATABASE CEIBAL_DB;

-- ─── RAW ─────────────────────────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS RAW;

CREATE OR REPLACE TABLE RAW.ACTIVIDAD_ESTUDIANTES (
    ID_PERSONA              VARCHAR,
    SEXO                    VARCHAR,
    ROL                     VARCHAR,
    DEPARTAMENTO            VARCHAR,
    SUBSISTEMA              VARCHAR,
    CICLO                   VARCHAR,
    GRADO                   VARCHAR,
    ZONA                    VARCHAR,
    CONTEXTO                VARCHAR,
    ANIO_LECTIVO            VARCHAR,
    CREA_DIAS_INGRESO       VARCHAR,
    CREA_ENTREGAS_TAREAS    VARCHAR,
    CREA_COMENTARIOS        VARCHAR,
    CREA_ACCIONES_TOTALES   VARCHAR,
    MATIFIC_DIAS_INGRESO    VARCHAR,
    MATIFIC_EPISODIOS       VARCHAR,
    BIBLIOTECA_DIAS_INGRESO VARCHAR,
    BIBLIOTECA_PRESTAMOS    VARCHAR
);
