CREATE DATABASE IF NOT EXISTS CEIBAL_DB;

USE DATABASE CEIBAL_DB;

-- ─── RAW ─────────────────────────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS RAW;

CREATE OR REPLACE TABLE RAW.ACTIVIDAD_ESTUDIANTES (
    ID_PERSONA              VARCHAR,
    SEXO                    VARCHAR,
    ROL                     VARCHAR,
    DEPARTAMENTO            VARCHAR,
    SUBSISTEMA              VARCHAR,
    CICLO                   VARCHAR,
    GRADO                   VARCHAR,
    ZONA                    VARCHAR,
    CONTEXTO                VARCHAR,
    ANIO_LECTIVO            VARCHAR,
    CREA_DIAS_INGRESO       VARCHAR,
    CREA_ENTREGAS_TAREAS    VARCHAR,
    CREA_COMENTARIOS        VARCHAR,
    CREA_ACCIONES_TOTALES   VARCHAR,
    MATIFIC_DIAS_INGRESO    VARCHAR,
    MATIFIC_EPISODIOS       VARCHAR,
    BIBLIOTECA_DIAS_INGRESO VARCHAR,
    BIBLIOTECA_PRESTAMOS    VARCHAR
);

-- ─── MART ────────────────────────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS MART;

CREATE OR REPLACE TABLE MART.DIM_ESTUDIANTE (
    SK_ESTUDIANTE   INTEGER PRIMARY KEY,
    ID_PERSONA      VARCHAR NOT NULL,
    SEXO            VARCHAR
);

CREATE OR REPLACE TABLE MART.DIM_TIEMPO (
    SK_TIEMPO       INTEGER PRIMARY KEY,
    ANIO_LECTIVO    INTEGER NOT NULL
);

CREATE OR REPLACE TABLE MART.DIM_GEOGRAFIA (
    SK_GEOGRAFIA    INTEGER PRIMARY KEY,
    DEPARTAMENTO    VARCHAR,
    ZONA            VARCHAR
);

CREATE OR REPLACE TABLE MART.DIM_CONTEXTO (
    SK_CONTEXTO     INTEGER PRIMARY KEY,
    SUBSISTEMA      VARCHAR,
    CICLO           VARCHAR,
    GRADO           VARCHAR,
    CONTEXTO        VARCHAR
);

CREATE OR REPLACE TABLE MART.FACT_ACTIVIDAD (
    SK_ESTUDIANTE           INTEGER NOT NULL,
    SK_TIEMPO               INTEGER NOT NULL,
    SK_GEOGRAFIA            INTEGER NOT NULL,
    SK_CONTEXTO             INTEGER NOT NULL,
    CREA_DIAS_INGRESO       FLOAT,
    CREA_ENTREGAS_TAREAS    FLOAT,
    CREA_COMENTARIOS        FLOAT,
    CREA_ACCIONES_TOTALES   FLOAT,
    MATIFIC_DIAS_INGRESO    FLOAT,
    MATIFIC_EPISODIOS       FLOAT,
    BIBLIOTECA_DIAS_INGRESO FLOAT,
    BIBLIOTECA_PRESTAMOS    FLOAT,
    FOREIGN KEY (SK_ESTUDIANTE) REFERENCES MART.DIM_ESTUDIANTE(SK_ESTUDIANTE),
    FOREIGN KEY (SK_TIEMPO)     REFERENCES MART.DIM_TIEMPO(SK_TIEMPO),
    FOREIGN KEY (SK_GEOGRAFIA)  REFERENCES MART.DIM_GEOGRAFIA(SK_GEOGRAFIA),
    FOREIGN KEY (SK_CONTEXTO)   REFERENCES MART.DIM_CONTEXTO(SK_CONTEXTO)
);

-- ─── RAW por año ─────────────────────────────────────────────────────────────
-- Nota: estas tablas las crea load_raw.py automáticamente.
-- Este DDL es referencia para inspección manual.

CREATE TABLE IF NOT EXISTS RAW.ACTIVIDAD_ESTUDIANTES_2025 (
    ID_PERSONA              VARCHAR,
    SEXO                    VARCHAR,
    ROL                     VARCHAR,
    DEPARTAMENTO            VARCHAR,
    SUBSISTEMA              VARCHAR,
    CICLO                   VARCHAR,
    GRADO                   VARCHAR,
    ZONA                    VARCHAR,
    CONTEXTO                VARCHAR,
    ANIO_LECTIVO            VARCHAR,
    CREA_DIAS_INGRESO       VARCHAR,
    CREA_ENTREGAS_TAREAS    VARCHAR,
    CREA_COMENTARIOS        VARCHAR,
    CREA_ACCIONES_TOTALES   VARCHAR,
    MATIFIC_DIAS_INGRESO    VARCHAR,
    MATIFIC_EPISODIOS       VARCHAR,
    BIBLIOTECA_DIAS_INGRESO VARCHAR,
    BIBLIOTECA_PRESTAMOS    VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW.ACTIVIDAD_ESTUDIANTES_2024 (
    ID_PERSONA              VARCHAR,
    SEXO                    VARCHAR,
    ROL                     VARCHAR,
    DEPARTAMENTO            VARCHAR,
    SUBSISTEMA              VARCHAR,
    CICLO                   VARCHAR,
    GRADO                   VARCHAR,
    ZONA                    VARCHAR,
    CONTEXTO                VARCHAR,
    ANIO_LECTIVO            VARCHAR,
    CREA_DIAS_INGRESO       VARCHAR,
    CREA_ENTREGAS_TAREAS    VARCHAR,
    CREA_COMENTARIOS        VARCHAR,
    CREA_ACCIONES_TOTALES   VARCHAR,
    MATIFIC_DIAS_INGRESO    VARCHAR,
    MATIFIC_EPISODIOS       VARCHAR,
    PAM_DIAS_INGRESO        VARCHAR,
    PAM_ACTIVIDADES         VARCHAR,
    BIBLIOTECA_DIAS_INGRESO VARCHAR,
    BIBLIOTECA_PRESTAMOS    VARCHAR
);
